---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE)
knitr::opts_knit$set(root.dir = "../")
```



```{r, warning=F, message=F}

########################################################
# LOAD PACKAGES
########################################################

library(tidyverse)
library(broom)
library(data.table)
library(matrixStats)
library(Biobase)
library(limma)
library(GEOquery)

# DIFFERENTIAL MOTIF BINDING
library(dbr)
########################################################
# DOWNLOAD OPEN SOURCE DATA THEN SPECIFY GENE-BY-GENE REGRESSION MODEL
########################################################

dat = getGEO("GSE77164")[[1]]

```

```{r}

y <- dat %>% exprs
X <- 
  dat %>% 
  pData %>% 
  select(age = `age:ch1`, 
         soldier = `childsoldier:ch1`, 
         edu = `educationlevel:ch1`)
X     <- model.matrix(~age + soldier + edu, data = X)
of_in <- "soldier1" 
# "of_in" = scalar parameter of interest: currently must identify a *single*
# column of "design", i.e. db is not currently sufficiently general to handle
# general factor vectors.

########################################################
# ESTIMATE MODEL USING STANDARD limmma/edgeR PIPELINE
# BUT STORE AS A TIDY TOP TABLE (tT) WITH A ROW CALLED "gene"
########################################################

ttT <- 
  lmFit(y, X) %>%
  eBayes %>%
  topTable(coef = of_in, n = Inf) %>% 
  tidy_topTable

########################################################
# DO DB INFERENCE AND EXTRACT RESULTS.
# THE FUNCTION "extracter" GIVES A TABLE OF P-VALUES FOR DIFFERENT METHODS:
# p_uni  = SIMPLE UNIVARIATE REGRESSION OF B ON EACH TFBM
# p_cov  = MULTPLE REGRESSION OF B ON ALL TFBM's SIMULTANIOUSLY
# p_tot  = SIMPLE UNIVARIATE OF B ON THE TOTAL NUMBER SITES (NOT SPECIFIC TO ONE TFBM)
# p_par  = parametric telis, RETURNED  ONLY IF ARGUMENT 'tT_sub' IS GIVEN TO "db" 
# p_npar = nonparametric telis, RETURNED  ONLY IF ARGUMENT 'tT_sub' IS GIVEN TO "db" 
########################################################

# BECAUSE tT_sub IS NOT SPECIFIED THESE TWO EXAMPLES JUST CALCULATE
# UNIVARIATE (UNI) AND MULTIPLE (COV) REGRESSIONS OF ON TFBM MATRIX 
# ONLY EXAMINE ONE TFBM: AR_
# IN THIS CASE ALL THREE REGRESSIONS ARE EQUIVALENT
ttT %>% 
  infer_db(which_tfbms = "AR") %>% 
  extract_db

# THE OTHER EXTREME (ALL TFBMS): BEWARE MULTIPLICITY
ttT %>% 
  infer_db %>% 
  extract_db

# NOTE: p_tot IS JUST ONE REGRESSION (OF DIFFERENTIAL EFFECT), THE RESULT IS
# REPLICATED FOR CONVENIENCE

########################################################
# TELIS AND REGRESSION:
# A MORE ELABORATE EXAMPLE WITH OPTIONAL PARAMETERS
######################################################## 
# HEURISTICAL FILTER ON UNCORRECTED P.VALUE, OR logFC, NOT AN INFERENCE
# OPTIONALLY SELECT TFBM MATRIX "which_matrix"
# OPTIONALLY SELECT INTERESTING TFBMS "which_tfbms" 
# OPTIONAL SET OF METHODS (p_npar, p_par, which require tT_sub be specified)

# db 
ttT %>% 
  infer_db(ttT_sub        = filter(ttT, P.Value <= 0.05),  
           which_matrix   = c("exonic1_utr1") ,
           which_tfbms    =  c("ALX3", "ALX4_TBX21", "AR") ,
           n_sim          = 10000) %>% 
  extract_db(methods =  c("p_npar", "p_par"))


```
