---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE)
knitr::opts_knit$set(root.dir = "../")
```



```{r, warning=F, message=F}

########################################################
# THIS VIGNETTE ONLY WORKS IF ONCE YOU HAVE LOGGED ONTO THE ADDHEALTH LONGLEAF
# SERVER (BECAUSE THE DATA IS PROTECTED)
########################################################

library(tidyverse)
library(data.table)
library(broom)
library(matrixStats)
library(Biobase)
library(limma)
library(GEOquery)
library(edgeR)

old_na_action <- options('na.action') # model.matrix() FUSSY ABOUT NA
options(na.action='na.pass')

```

```{r} 

# DIFFERENTIAL MOTIF BINDING
source("R/utility_tfbm.R")
########################################################
# LOAD DATA
########################################################

# dat = readRDS("/ifs/sec/cpc/addhealth/RNA/share/zurich_subjects/dt.rds") # longleaf
dat     <- readRDS("/Volumes/Share/wenjia_from_j/addhealth/data/dt.rds") # local

# FILTER OUT UNEXPRESSED GENES
e_genes <- filterByExpr(exprs(dat))
e_genes <- names(e_genes[e_genes == TRUE])

# SPECIFY GENE-BY-GENE REGRESSION MODEL
rhs       <- "male + raceth + Plate + AvgCorrelogram100 + w5eversmoke"
counts    <- dat[e_genes, ] %>% exprs
phen      <- dat[e_genes, ] %>% pData
design    <- model.matrix(as.formula(str_c("~", rhs)), data = phen)
of_in     <- "w5eversmoke" # scalar parameter of interest: should identify a *single* column of "design"

########################################################
# ESTIMATE TIDY topTable (limma)
########################################################

ttT <-
  voom(counts = counts[, complete.cases(design)],
     design = design[complete.cases(design), ]) %>% # arrayWeights %>%
  lmFit %>%
  eBayes %>%
  topTable(coef = of_in, n = Inf) %>% 
  tidy_topTable

########################################################
# INSPECT DB RESULTS
########################################################

# regression only
ttT %>%
  infer_db %>%
  extract_db
# telis and regression
ttT %>%
  infer_db(ttT_sub = filter(ttT, P.Value <= 0.05)) %>%
  extract_db

########################################################
# REINSTATE OLD na.action
########################################################
options(na.action = old_na_action)

```
